"use client";

import { useState } from "react";
import { TrendingUp, TrendingDown, Users, BarChart3, ArrowRight, Sparkles } from "lucide-react";
import { cn } from "@/lib/utils";

interface InsightCard {
  title: string;
  body: string;
  type: string;
}

interface Digest {
  id: string;
  weekOf: string;
  insightsJson: InsightCard[];
  plainText: string;
  generatedAt: string;
}

const TYPE_META: Record<string, { icon: React.ReactNode; color: string }> = {
  top_performer: { icon: <TrendingUp className="w-4 h-4" />, color: "text-green-400 bg-green-400/10" },
  bottom_performer: { icon: <TrendingDown className="w-4 h-4" />, color: "text-red-400 bg-red-400/10" },
  profitable_shift: { icon: <BarChart3 className="w-4 h-4" />, color: "text-blue-400 bg-blue-400/10" },
  unprofitable_shift: { icon: <BarChart3 className="w-4 h-4" />, color: "text-orange-400 bg-orange-400/10" },
  repeat_rate_trend: { icon: <Users className="w-4 h-4" />, color: "text-purple-400 bg-purple-400/10" },
  reallocation: { icon: <ArrowRight className="w-4 h-4" />, color: "text-yellow-400 bg-yellow-400/10" },
};

export default function DigestPanel({ digest }: { digest: Digest | null }) {
  if (!digest) {
    return (
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-10 text-center">
        <Sparkles className="w-8 h-8 text-slate-600 mx-auto mb-3" />
        <p className="text-slate-500 text-sm">Your first weekly digest is being generated. Check back soon.</p>
      </div>
    );
  }

  const insights: InsightCard[] = Array.isArray(digest.insightsJson) ? digest.insightsJson : [];

  return (
    <div className="space-y-3">
      <div className="flex items-center justify-between mb-1">
        <span className="text-slate-400 text-xs">
          Week of {new Date(digest.weekOf).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}
        </span>
        <span className="text-xs text-slate-600">Generated by AI</span>
      </div>

      {insights.map((insight, i) => {
        const meta = TYPE_META[insight.type] || TYPE_META.top_performer;
        return (
          <div key={i} className="bg-slate-900 border border-slate-800 rounded-xl p-4">
            <div className="flex items-center gap-2 mb-2">
              <span className={cn("flex items-center gap-1.5 text-xs font-semibold px-2 py-1 rounded-full", meta.color)}>
                {meta.icon}
                {insight.type.replace(/_/g, " ")}
              </span>
            </div>
            <div className="font-semibold text-slate-100 text-sm mb-1">{insight.title}</div>
            <div className="text-slate-400 text-sm leading-relaxed">{insight.body}</div>
          </div>
        );
      })}

      {insights.length === 0 && (
        <div className="text-slate-500 text-sm text-center py-6">No insights available yet.</div>
      )}
    </div>
  );
}
